language: node_js
node_js: '12.8.0'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn build
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_9df516b5f496_key -iv $encrypted_9df516b5f496_iv
    -in deploy__key.enc -out ~/.ssh/id_rsa -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - ssh root@$SERVERIP -o StrictHostKeyChecking=no 'cd $SERVERDIR && git pull && npm install && npm run build'
  # - cd ./dist
  # - git init
  # - git config user.name "travis"
  # - git config user.email "travis"
  # - git add .
  # - git commit -m "update deploy"
  # - git push --force git@github.com:lzw1604748707/anshuye-server-ts.git master:deploy
