language: node_js
node_js: '-10.16.0'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn build
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_9df516b5f496_key -iv $encrypted_9df516b5f496_iv
    -in deploy__key.enc -out ./deploy__key -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - scp -rB ./dist root@$SERVERIP:$SERVERDIR
