language: node_js
node_js: '12.8.0'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn build
branches:
  only:
    - master
before_install:
  # - openssl aes-256-cbc -K $encrypted_9df516b5f496_key -iv $encrypted_9df516b5f496_iv
  #   -in deploy__key.enc -out ./deploy__key -d
after_success:
  - cd ./dist
  - git init
  - git config user.name "travis"
  - git config user.email "travis"
  - git add .
  - git commit -m "更新部署"
  - git push --force  origin master:deploy
